# Generated by Django 4.2.28 on 2026-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="admin_share",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="lawyer_share",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
